"""add document summary fields

Revision ID: 969592b1859f
Revises: cb0fdef61194
Create Date: 2026-09-21 16:49:44.140154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969592b1859f'
down_revision: Union[str, Sequence[str], None] = 'cb0fdef61194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('summary_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'summary_generated_at')
    op.drop_column('documents', 'summary')
    # ### end Alembic commands ###
